# Site settings
baseurl = "http://devict.github.io/ictgamejam/"
languageCode = "en-us"
title = "ICT Game Jam"
theme = "hugo-agency-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) or
	# most longer texts.
	#
	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "ICT Game Jam"
	description = "The best gamedev event in the midwest!"

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
	email = "ictgamejam@makeict.org"

    # Link custom assets relative to /statuc
    custom_css = []
    custom_js  = []


	# Navigation
	[params.navigation]
		brand = "July 15-17 2016"
		event = "Event"
		schedule = "Schedule"
		help = "Help!"
		services = "Services"
		portfolio = "Portfolio"
		about = "About"
		team = "Judges"
		contact = "Contact"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #    url = "http://gohugo.io"
    #    name = "Hugo"
    #    weight = 10

    # postpended links
    [[menu.postpend]]
        url = "http://makeict.wildapricot.org/event-2267694"
        name = "RSVP!"
        weight = 10


	# Hero section
	[params.hero]
		# To change the background image of the hero, replace 'header-bg.jpg' in
		# the 'static/img' folder.
		# title = "Welcome To Our Studio!"
		# subtitle = "It's nice to meet you"
		buttonText = "What's a game jam?"


	# Event section
	[params.event]
        enable = true
		title = "It's a PARTY"
		subtitle = "Ok, **technically** it's a competition with cash prizes.  It's not a workshop or a class about making games.  But if you want to spend a weekend learning gamedev and getting fed, you'll be in good company.<br><br><a href=\"http://makeict.wildapricot.org/event-2267694\" class=\"page-scroll btn btn-xl\">You should definitely RSVP</a>."

        [[params.event.row]]

						[[params.event.row.list]]
								icon = "fa-gamepad"
								title = "Do I need to have made a game before?"
								description = "[Last year](http://devict.org/gamejam), over 60% of participants had little or no gamedev experience, but they had a blast.  We'll have lots of people willing to answer questions and help you learn at your own pace!"

            [[params.event.row.list]]
                icon = "fa-code"
                title = "Do I need to be a programmer?"
                description = "No!  Games also need artists, writers, and designers.  There is no rule for whether your game must be 2D, 3D, complex, or even have graphics."

            [[params.event.row.list]]
                icon = "fa-laptop"
                title = "Do I need a computer?"
                description = "While it's best to bring your own, there will even be computers available, just bring something for saving your work!  For those who bring their own, your desk will have 2 external monitors."

						[[params.event.row.list]]
                icon = "fa-heart"
                title = "I love it! I must know more!"
                description = "If you insist!  The event is generously hosted at [NCAT](http://ncatkansas.org/).  We will have snacks, drinks and T-shirt waiting for you!  All meals on Saturday, breakfast and lunch provided on Sunday.  All that's left is to [RSVP](http://makeict.wildapricot.org/event-2267694) and follow [@ICTGameJam](https://twitter.com/ICTGameJam)!"


	# Schedule timeline
	[params.schedule]
	      enable = true
		title = "Schedule"
		subtitle = "Great!  Now that you're going to the game jam, here's how the weekend will go..."
		endpoint = "Keep<br>making<br>games!"

		# The events will be listed from the top to the bottom.
		# All images are stored under 'static/img/about'.
		# Replace them with your own.
		[[params.schedule.events]]
			img= "1.jpg"
			date = "Friday"
			title = "Kickoff!"
			description = "Doors open at 5pm, kickoff slides and intro start at 6pm.  Participants will receive an email to vote on the game jam's theme.  Those needing teams will have an opportunity to pitch ideas and form or join teams as necessary.  You can even work solo if you want.  Then it's time to start making games!"

		[[params.schedule.events]]
			img = "2.jpg"
			date = "Saturday"
			title = "Build Day!"
			description = "Show up bright and early.  Enjoy refreshments, 3 meals and ... oh yeah... build a game!  Hit a wall?  Ask for help!  Lean on the volunteers and fellow game devs for feedback and encouragement!"

		[[params.schedule.events]]
			img = "3.jpg"
			date = "Sunday"
			title = "Polish, SHIP IT!!  Community Play.  Winners announced!"
			description = "Put the finishing touches on your game.  Work stops at 1pm.  Doors open to the public 3 - 5pm to play your games and vote for Community Choice while the judges deliberate.  Winners announced at 5:30pm."

	# help section
	[params.help]
        enable = true
		title = "Help!"
		subtitle = "The best way to help is to [RSVP](http://makeict.wildapricot.org/event-2267694) and participate!  Otherwise we welcome volunteered time or talent in any amount before, during or after the event.<br><br>Finally, if you absolutely insist, here are some sponsorship packages to consider!  For all these, please contact ictgamejam@makeict.org.<br><br>This and all devICT gamedev events are operated under MakeICT, a 501c3 organization.  All donations are used to run this and future gamedev events."

        [[params.help.row]]

            [[params.help.row.list]]
                icon = "fa-wrench"
                title = "Italian Plumber 1-1: $250"
                description = "<i class=\"fa fa-caret-right\"></i> Thanks via ICT Game Jam (Twitter), MakeICT and devICT (Twitter, Facebook), twice before event.<br><i class=\"fa fa-caret-right\"></i> Thanks at Friday kickoff presentation, and awards announcements on Sunday.<br><i class=\"fa fa-caret-right\"></i> Logo or name on back of event T-shirt, and on 2016 event page.  Note: Inclusion on T-shirt requires sponsorship prior to July 1st 2016."

            [[params.help.row.list]]
                icon = "fa-arrow-up"
                title = "Protein Mushroom: $500"
                description = "<i class=\"fa fa-caret-right\"></i> Everything from Italian Plumber 1-1 package.<br><i class=\"fa fa-caret-right\"></i> Display of provided promotional banner at event.<br><i class=\"fa fa-caret-right\"></i> Inclusion of any desired promotional items or material in participantsâ€™ swag packs."

            [[params.help.row.list]]
                icon = "fa-star"
                title = "Invincibility: $1500"
                description = "<i class=\"fa fa-caret-right\"></i> Everything in Protein Mushroom package.<br><i class=\"fa fa-caret-right\"></i> Table space at event for provided promotional material.<br><i class=\"fa fa-caret-right\"></i> Logo or name displayed in all event videos."

						[[params.help.row.list]]
                icon = "fa-car"
                title = "Blue Shell: $3000"
                description = "<i class=\"fa fa-caret-right\"></i> Everything in Invincibility package.<br><i class=\"fa fa-caret-right\"></i> Monthly thanks via social media through May 2017.<br><i class=\"fa fa-caret-right\"></i> Table, banner space, and sponsorship thanks at 2 devICT Gamedev Build or Demo Days."


	# Services section
	[params.services]
        enable = false
		title = "Services"
		subtitle = "Lorem ipsum dolor sit amet consectetur."

        [[params.services.row]]

            [[params.services.row.list]]
                icon = "fa-shopping-cart"
                title = "E-Commerce"
                description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."

            [[params.services.row.list]]
                icon = "fa-laptop"
                title = "Responsive Design"
                description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."

            [[params.services.row.list]]
                icon = "fa-lock"
                title = "Web"
                description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."

	# Portfolio section
	[params.portfolio]
        enable = false
		# All projects defined in their own files. You can find example projects
		# at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
		# at the root of this Hugo site.
		# For more informtion take a look at the README.
		title = "Portfolio"
		subtitle = "Lorem ipsum dolor sit amet consectetur."

		[params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttonText = "Close project"


  # About section

	[params.about]
        enable = false
		title = "About"
		subtitle = "Lorem ipsum dolor sit amet consectetur."
		endpoint = "Be part<br>of our<br>story!"

		# The events will be listed from the top to the bottom.
		# All images are stored under 'static/img/about'.
		# Replace them with your own.
		[[params.about.events]]
			img = "1.jpg"
			date = "2009-2011"
			title = "Our Humble Beginnings"
			description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

		[[params.about.events]]
			img = "2.jpg"
			date = "March 2011"
			title = "An Agency is Born"
			description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

		[[params.about.events]]
			img = "3.jpg"
			date = "December 2012"
			title = "Our Humble Beginnings"
			description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

		[[params.about.events]]
			img = "4.jpg"
			date = "July 2014"
			title = "Phase Two Expansion"
			description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"


	# Team section
	[params.team]
        enable = false
		title = "Our amazing team"
		subtitle = "Lorem ipsum dolor sit amet consectetur."
		description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde."

		# All team member's pictures are stored under 'static/img/team'.
		# Replace them with your own too.
		[[params.team.members]]
			img = "1.jpg"
			name = "Kay Garland"
			position = "Lead Designer"
			social = [
				["fa-twitter", "#"],
				["fa-facebook", "#"],
				["fa-linkedin", "#"]
			]

		[[params.team.members]]
			img = "2.jpg"
			name = "Larry Parker"
			position = "Lead Marketer"
			social = [
				["fa-twitter", "#"],
				["fa-facebook", "#"],
				["fa-linkedin", "#"]
			]

		[[params.team.members]]
			img = "3.jpg"
			name = "Diana Pertersen"
			position = "Lead Developer"
			social = [
				["fa-twitter", "#"],
				["fa-facebook", "#"],
				["fa-linkedin", "#"]
			]

	# Client section
    [params.clients_list]
        enable = true
				title = "Our amazing sponsors"
				subtitle = "Thanks for making this event possible!!"

    	# All the clients' logos are stored under 'static/img/logos'.
    	# Replace them with your clients's logos.
    	[[params.clients]]
    		logo = "devict_logo_260.png"
    		link = "http://devict.org"

    	[[params.clients]]
    		logo = "MakeICT-260.png"
    		link = "http://makeict.org"

    	[[params.clients]]
    		logo = "Storehouse-Logo-260.png"
    		link = "https://sthse.co/"

    	[[params.clients]]
    		logo = "ncat-logo-210.png"
    		link = "http://ncatkansas.org"

	# Contact section
	[params.contact]
        enable = false
		title = "Contact us"
		subtitle  = "Lorem ipsum dolor sit amet consectetur."
		buttonText = "Send message"

		# 'warning' defines error messages for invalid inputs
		[params.contact.form.name]
			text = "Your Name *"
			warning = "Please enter your name."

		[params.contact.form.email]
			text = "Your Email *"
			warning = "Please enter your email address."

		[params.contact.form.phone]
			text = "Your Phone *"
			warning = "Please enter your phone number."

		[params.contact.form.message]
			text = "Your Message *"
			warning = "Please enter a message."


	# Footer section
	[params.footer]
        enable = true
		copyright = "Published under the Apache License 2.0."

		[[params.footer.social]]
			icon = "fa-twitter"
			link = "https://twitter.com/ICTGameJam"

		[[params.footer.social]]
			icon = "fa-facebook"
			link = "https://www.facebook.com/developerict/"

		[[params.footer.quicklinks]]
			text = "devICT"
			link = "http://devict.org/"

		[[params.footer.quicklinks]]
			text = "Email ICT Game Jam"
			link = "mailto:ictgamejam@makeict.org"
